# Assertion : if this exception is thrown, the involved code that produced it is sure to have a bug.
#0 : Wrong index returned by findColumn.
#1 : Field name that caused the wrong calculation. 
assert.wrong_index_for_column_name=[Erreur interne de l''API] The column index {0}, illegal, has been returned by findColumn for the field ''{1}''.

# Exception : field is not a date. 
#0 : Field name.
#1 : SQL Query.
#2 : Field value that is not a date.
excp.field_is_not_a_date=The field {0} in the query ''{1}'' has a ''{2}'' value that is not a date. 

# Exception : field is not numeric. 
#0 : Field name.
#1 : Field type.
#2 : SQL Query.
#3 : Field value that is not a number.
excp.field_is_not_numeric=The field {0} of type {1} in the query ''{2}'' has a ''{3}'' value that is not numeric. 

# Exception thrown when the resultset has no more results.
#0 : SQL Query that was attempted but failed.
#1 : Database name.
excp.no_more_results=The result set has no more results for the SQL request ''{0}'' on database {1}.

# Log : a string value has been converted with a charset.
#0 : Field name.
#1 : Field value after being converted with the charset.
#2 : Charset used.
log.string_field_charset=String field name ''{0}'' bytes values converted to ''{1}'' using charset {2}.
